---

- name: copy - delete_catalog_backup
  copy:
    src: delete_catalog_backup
    dest: /usr/libexec/bacula/delete_catalog_backup
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rx,o=rx'

- name: template - bacula-bootstrap-backup
  template:
    src: bacula-bootstrap-backup
    dest: /usr/libexec/bacula/bacula-bootstrap-backup
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rx,o=rx'

- name: run bacula-bootstrap-backup
  command: /usr/libexec/bacula/bacula-bootstrap-backup
  become: true
  become_user: bacula
  become_method: sudo

- name: Assemble dir for backup scripts
  file:
    path: /usr/libexec/bacula/backup-scripts
    state: directory
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'

- name: Create before_backup script header
  template:
    src: before_backup_head.j2
    dest: /usr/libexec/bacula/backup-scripts/00.before_backup
    owner: bacula
    group: tape
    mode: 'u=rw,g=rw,o=r'

- name: Create before_backup script footer
  template:
    src: before_backup_foot.j2
    dest: /usr/libexec/bacula/backup-scripts/99.before_backup
    owner: bacula
    group: tape
    mode: 'u=rw,g=rw,o=r'

- name: Create after_backup script header
  template:
    src: after_backup_head.j2
    dest: /usr/libexec/bacula/backup-scripts/00.after_backup
    owner: bacula
    group: tape
    mode: 'u=rw,g=rw,o=r'

- name: Create after_backup script footer
  template:
    src: after_backup_foot.j2
    dest: /usr/libexec/bacula/backup-scripts/99.after_backup
    owner: bacula
    group: tape
    mode: 'u=rw,g=rw,o=r'

# *****************************************************************************
# Assemble the backup scripts if the assemble_scripts variable is set

- name: Assemble bacula before_backup script
  assemble:
    src: /usr/libexec/bacula/backup-scripts/
    regexp: '\d\d[.]before_backup.*'
    dest: /usr/libexec/bacula/before_backup
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
  when: assemble_scripts

- name: Assemble bacula after_backup script
  assemble:
    src: /usr/libexec/bacula/backup-scripts/
    regexp: '\d\d[.]after_backup.*'
    dest: /usr/libexec/bacula/after_backup
    owner: bacula
    group: tape
    mode: 'u=rwx,g=rwx,o=rx'
  when: assemble_scripts

- name: remove assemble dir for backup scripts
  file:
    path: /usr/libexec/bacula/backup-scripts
    state: absent
  when: assemble_scripts

# *****************************************************************************
# Install selinux policies

- import_tasks: selinux-script-policy.yml
